on: [push, pull_request]
name: snapshot
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "TAG_NAME=$(date)" >> $GITHUB_ENV
          echo "RELEASE_NAME=somerelease" >> $GITHUB_ENV
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
