on: [push, pull_request]
name: snapshot
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "SNAPSHOT_VERSION=8.0-$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
      - name: Test with environment variables
        run: |
          echo "direct: $SNAPSHOT_VERSION"
          echo "through env: $SNAPSHOT_VERSION_ENV"
        env:
          SNAPSHOT_VERSION_ENV: ${{ env.SNAPSHOT_VERSION }}
