on: [push, pull_request]
name: snapshot
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "SNAPSHOT_SUFFIX=8.0-$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
      - name: Test with environment variables
        run: echo $SNAPSHOT_SUFFIX
